/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/plex/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plex Pin */
        post: operations["create_plex_pin_api_v1_auth_plex_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/plex/pin/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll Plex Pin */
        post: operations["poll_plex_pin_api_v1_auth_plex_pin_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local Login */
        post: operations["local_login_api_v1_auth_local_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Settings */
        get: operations["get_admin_settings_api_v1_settings_get"];
        /** Put Admin Settings */
        put: operations["put_admin_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regions */
        get: operations["get_regions_api_v1_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Services */
        get: operations["get_services_api_v1_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connection-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_v1_connection_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home */
        get: operations["get_home_api_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rails */
        get: operations["get_rails_api_v1_rails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/title/{media_type}/{tmdb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Title */
        get: operations["get_title_api_v1_title__media_type___tmdb_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Availability */
        post: operations["post_availability_api_v1_availability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Request */
        post: operations["create_request_api_v1_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Signal */
        post: operations["post_signal_api_v1_signals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Title */
        get: operations["explain_title_api_v1_recommendations_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Profile */
        post: operations["reset_profile_api_v1_recommendations_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accent
         * @enum {string}
         */
        Accent: "crimson" | "azure" | "violet" | "emerald" | "amber";
        /** Appearance */
        Appearance: {
            /** @default dark */
            theme: components["schemas"]["Theme"];
            /** @default crimson */
            accent: components["schemas"]["Accent"];
        };
        /**
         * Availability
         * @description A title's library status. `known` is false only when Seerr was unreachable —
         *     distinguishing "Seerr says not-in-library" from "we couldn't reach Seerr".
         */
        Availability: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "partial" | "processing" | "pending" | "not_requested" | "unknown";
            /** Known */
            known: boolean;
        };
        /** AvailabilityItem */
        AvailabilityItem: {
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Id */
            id: number;
        };
        /** AvailabilityRequest */
        AvailabilityRequest: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["AvailabilityItem"][];
        };
        /**
         * ConnectionTarget
         * @enum {string}
         */
        ConnectionTarget: "tmdb" | "seerr";
        /** ConnectionTestRequest */
        ConnectionTestRequest: {
            target: components["schemas"]["ConnectionTarget"];
        };
        /** ConnectionTestResponse */
        ConnectionTestResponse: {
            target: components["schemas"]["ConnectionTarget"];
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Personalized */
            personalized: boolean;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
        };
        /** Genre */
        Genre: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Tmdb Configured */
            tmdb_configured: boolean;
            /** Seerr Configured */
            seerr_configured: boolean;
        };
        /** HeroSlide */
        HeroSlide: {
            item: components["schemas"]["MediaSummary"];
            /** Logo Path */
            logo_path: string | null;
            trailer: components["schemas"]["Video"] | null;
            /** Certification */
            certification: string | null;
            /** Runtime */
            runtime: number | null;
            /**
             * Genres
             * @default []
             */
            genres: string[];
        };
        /** HomeFeed */
        HomeFeed: {
            /**
             * Hero
             * @default []
             */
            hero: components["schemas"]["HeroSlide"][];
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["Rail"][];
        };
        /** LocalLoginRequest */
        LocalLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MediaDetail */
        MediaDetail: {
            /** Id */
            id: number;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Title */
            title: string;
            /** Overview */
            overview: string;
            /** Poster Path */
            poster_path: string | null;
            /** Backdrop Path */
            backdrop_path: string | null;
            /** Year */
            year: number | null;
            /** Vote Average */
            vote_average: number;
            /** Tagline */
            tagline: string;
            /** External Url */
            external_url: string;
            /**
             * Genres
             * @default []
             */
            genres: components["schemas"]["Genre"][];
            /** Runtime */
            runtime: number | null;
            /** Release Date */
            release_date: string | null;
            /** Certification */
            certification: string | null;
            /** Logo Path */
            logo_path: string | null;
            trailer: components["schemas"]["Video"] | null;
            /**
             * Cast
             * @default []
             */
            cast: components["schemas"]["Person"][];
            /**
             * Crew
             * @default []
             */
            crew: components["schemas"]["Person"][];
            watch: components["schemas"]["WatchProviders"];
            /**
             * Recommendations
             * @default []
             */
            recommendations: components["schemas"]["MediaSummary"][];
            /**
             * Similar
             * @default []
             */
            similar: components["schemas"]["MediaSummary"][];
            /**
             * Seasons
             * @default []
             */
            seasons: components["schemas"]["SeasonSummary"][];
            /** Number Of Seasons */
            number_of_seasons: number | null;
            availability?: components["schemas"]["Availability"] | null;
            taste?: components["schemas"]["TasteFlags"] | null;
        };
        /** MediaSummary */
        MediaSummary: {
            /** Id */
            id: number;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Title */
            title: string;
            /** Overview */
            overview: string;
            /** Poster Path */
            poster_path: string | null;
            /** Backdrop Path */
            backdrop_path: string | null;
            /** Year */
            year: number | null;
            /** Vote Average */
            vote_average: number;
        };
        /** Person */
        Person: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Profile Path */
            profile_path: string | null;
        };
        /** PinCreateResponse */
        PinCreateResponse: {
            /** Pin Id */
            pin_id: string;
            /** Auth Url */
            auth_url: string;
        };
        /** PinPollRequest */
        PinPollRequest: {
            /** Pin Id */
            pin_id: string;
        };
        /** PinPollResponse */
        PinPollResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ok";
            user?: components["schemas"]["UserResponse"] | null;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Provider Id */
            provider_id: number;
            /** Name */
            name: string;
            /** Logo Path */
            logo_path: string | null;
        };
        /**
         * PublicConfig
         * @description The only settings shape ever serialized toward the client.
         *
         *     Built as an explicit allowlist projection — never by excluding fields from
         *     Settings — so a new secret field can never leak by default.
         */
        PublicConfig: {
            /** Tmdb Configured */
            tmdb_configured: boolean;
            /** Seerr Configured */
            seerr_configured: boolean;
            appearance: components["schemas"]["Appearance"];
        };
        /** Rail */
        Rail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @default standard
             * @enum {string}
             */
            kind: "standard" | "genre" | "top10";
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["MediaSummary"][];
        };
        /**
         * RailType
         * @enum {string}
         */
        RailType: "hero" | "my-list" | "trending" | "more-like" | "popular" | "recommended" | "services" | "genres" | "recent" | "top-rated" | "decades";
        /** RailTypeDescriptor */
        RailTypeDescriptor: {
            id: components["schemas"]["RailType"];
            /** Label */
            label: string;
        };
        /** RailsPage */
        RailsPage: {
            /**
             * Rails
             * @default []
             */
            rails: components["schemas"]["Rail"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** RegionOption */
        RegionOption: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** RegionsResponse */
        RegionsResponse: {
            /** Regions */
            regions: components["schemas"]["RegionOption"][];
        };
        /** RequestBody */
        RequestBody: {
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Tmdb Id */
            tmdb_id: number;
        };
        /**
         * RequestResponse
         * @description A single discriminated outcome the SPA branches on. `availability` is the new
         *     library status on success; `seerr_url` is the server-built "Request in Seerr"
         *     fallback (present whenever the external URL is configured).
         */
        RequestResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "re_auth_required" | "unavailable" | "failed";
            availability?: components["schemas"]["Availability"] | null;
            /** Seerr Url */
            seerr_url?: string | null;
        };
        /**
         * ResetResponse
         * @description `seeded_signals` is how many request-history signals the re-seed
         *     imported — 0 when the user has no history or Seerr was unreachable.
         */
        ResetResponse: {
            /** Seeded Signals */
            seeded_signals: number;
        };
        /** RuntimeSettings */
        RuntimeSettings: {
            /**
             * Region
             * @default US
             */
            region: string;
            /**
             * Service Ids
             * @default []
             */
            service_ids: number[];
            /**
             * Disabled Rail Types
             * @default []
             */
            disabled_rail_types: components["schemas"]["RailType"][];
            appearance?: components["schemas"]["Appearance"];
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["MediaSummary"][];
        };
        /** SeasonSummary */
        SeasonSummary: {
            /** Season Number */
            season_number: number;
            /** Name */
            name: string;
            /** Episode Count */
            episode_count: number;
            /** Air Date */
            air_date: string | null;
        };
        /** ServiceOption */
        ServiceOption: {
            /** Provider Id */
            provider_id: number;
            /** Name */
            name: string;
            /** Logo Path */
            logo_path: string | null;
            /** Display Priority */
            display_priority: number;
        };
        /** ServicesResponse */
        ServicesResponse: {
            /** Region */
            region: string;
            /** Services */
            services: components["schemas"]["ServiceOption"][];
        };
        /** SettingsResponse */
        SettingsResponse: {
            settings: components["schemas"]["RuntimeSettings"];
            /** Rail Types */
            rail_types: components["schemas"]["RailTypeDescriptor"][];
        };
        /** SignalBody */
        SignalBody: {
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "movie" | "tv";
            /** Tmdb Id */
            tmdb_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "detail_open" | "watchlist" | "not_interested";
            /**
             * Retract
             * @default false
             */
            retract: boolean;
        };
        /**
         * SignalResponse
         * @description `recorded` is whether a new row was written — idempotent toggle re-adds
         *     and same-day detail reopens succeed with `recorded: false`.
         */
        SignalResponse: {
            /** Recorded */
            recorded: boolean;
        };
        /**
         * TasteFlags
         * @description The caller's own toggle state for a title — resolved from their signals
         *     at read time so the detail modal renders current watchlist/hidden state.
         */
        TasteFlags: {
            /**
             * Watchlisted
             * @default false
             */
            watchlisted: boolean;
            /**
             * Hidden
             * @default false
             */
            hidden: boolean;
        };
        /**
         * Theme
         * @enum {string}
         */
        Theme: "dark" | "light";
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Is Admin */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Video */
        Video: {
            /** Key */
            key: string;
            /** Site */
            site: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Official */
            official: boolean;
        };
        /** WatchProviders */
        WatchProviders: {
            /**
             * Flatrate
             * @default []
             */
            flatrate: components["schemas"]["ProviderInfo"][];
            /**
             * Rent
             * @default []
             */
            rent: components["schemas"]["ProviderInfo"][];
            /**
             * Buy
             * @default []
             */
            buy: components["schemas"]["ProviderInfo"][];
            /**
             * Free
             * @default []
             */
            free: components["schemas"]["ProviderInfo"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    create_plex_pin_api_v1_auth_plex_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCreateResponse"];
                };
            };
        };
    };
    poll_plex_pin_api_v1_auth_plex_pin_poll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinPollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinPollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_login_api_v1_auth_local_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_admin_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_admin_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regions_api_v1_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionsResponse"];
                };
            };
        };
    };
    get_services_api_v1_services_get: {
        parameters: {
            query: {
                region: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_v1_connection_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_api_v1_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeFeed"];
                };
            };
        };
    };
    get_rails_api_v1_rails_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RailsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_title_api_v1_title__media_type___tmdb_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_type: "movie" | "tv";
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_availability_api_v1_availability_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Availability"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_v1_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_signal_api_v1_signals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_title_api_v1_recommendations_explain_get: {
        parameters: {
            query: {
                type: "movie" | "tv";
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_profile_api_v1_recommendations_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
        };
    };
}
